export const SITE = {
  name: "Internet Speed Test Tunisie",
  shortName: "SpeedTest TN",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://speedtest-tunisie.com",
  locale: "fr_TN",
  title: "Internet Speed Test Tunisie – Test de Vitesse Internet & Débit",
  tagline: "Test de vitesse internet Tunisie : mesurez votre débit de téléchargement, d'envoi et votre ping en quelques secondes.",
  description:
    "Test de vitesse internet gratuit en Tunisie. Mesurez votre débit de téléchargement et d'envoi, votre ping et la qualité de votre connexion WiFi, fibre, ADSL, 4G, 4G+ et 5G. Simple, rapide, sans inscription.",
  keywords: [
    "speed test tunisie",
    "test de vitesse internet tunisie",
    "test vitesse internet tunisie",
    "test débit internet tunisie",
    "speedtest tunisie",
    "test wifi tunisie",
    "test connexion internet tunisie",
    "test de vitesse tunisie",
    "vitesse internet tunisie",
    "débit internet tunisie",
    "test adsl tunisie",
    "test fibre tunisie",
    "test 4g tunisie",
    "test 4g+ tunisie",
    "test 5g tunisie",
    "test ping tunisie",
    "test latence tunisie",
    "speed test réseau tunisie",
    "internet vitesse tunisie",
    "tester sa connexion tunisie",
  ],
  author: "Internet Speed Test Tunisie",
} as const;